### ISSUE TITLE
Limit disk usage in CLIRI

### ISSUE THREAD

**Issue by alongalky** [iotaledger-archive/cliri#76]
With a high TPS, the database fills up fairly quickly, making it impossible to run CLIRI continuously. The eventual solution for this is local snapshots, but for testing / znet purposes we can do something simpler.

The problem: assuming we want to keep our database below 20 GB, over a period of 1 month, with each transaction taking around 1.6 KB, we can afford an average TPS of: `(20 * 1024 * 1024) / (1.6 * 28 * 24 * 60 * 60)≈5.4`, which is unacceptably low for testing purposes.

The solution we propose is to reset the database automatically every week (say on Sunday, UTC 00:00). This will allow us to run at around 21 TPS, and even if we go faster it will clear up by the following week. This is a temporary measure to get znet up and running, and not a replacement for local snaphsots.

**Comment by alon-e** [comment]
Open question:
How to implement this in a simple manner? 

I think the most simple way would be using Linux built-in scheduling ; either `cron` or a service with a `.timer`.

Process:
1. Shut down node
2. Update configuration timestamp
3. Delete DB
4. Start node

The problem is this won't be bundled in CLIRI, and will not offer a solution for windows (which is not a biggy imho). 

Otherwise we would need to purge queues and any in memory objects to avoid failures. (adding code to cliri that has no functional purpose)

Thoughts?

**Comment by alon-e** [comment]
Example of service timer:
https://github.com/georgewhewell/undervolt/blob/master/README.rst#running-automatically-on-boot

**Comment by alongalky** [comment]
I'm concerned it will make running a CLIRI node significantly harder. I'm not sure if it's worth the code simplicity.

**Comment by alon-e** [comment]
tasks in code:

- purge `TransactionRequester`
- purge `TipsViewModel`
- clearColumn for all columns - like in `rescanDb` but add Transaction
- set new timestamp - `snapshotTimestamp` (this needs to be re-introduced to CLIRI + allow updating not only in constructor [`TransactionValidator`])

- Block API for that time?
- Block Gossip for that time?
- Block DB.store() for that time?

**Comment by alon-e** [comment]
+ we might also need to purge `TransactionValidator.newSolidTransactionsOne`
